### ISSUE TITLE
repository name

### ISSUE THREAD

**Issue by dbu** [php-http/plugins#1]
i think this repository should be called "plugin", not "plugin-client". its about all aspects of plugins.

**Comment by sagikazarmark** [comment]
Singular or plural?

**Comment by dbu** [comment]
hm. maybe plugin-system?

**Comment by sagikazarmark** [comment]
httplugin LOL :stuck_out_tongue_winking_eye:

**Comment by joelwurtz** [comment]
plugin-stack ?

**Comment by sagikazarmark** [comment]
Actually it would be nice to play with the words: httplug and plug-in. Can we bring them together somehow?

**Comment by dbu** [comment]
or httplug-plugins. well...
but seriously, do we keep this name or go for plugin(s) or plugin-system?

**Comment by sagikazarmark** [comment]
Actually...it was a nice idea, but don't insist on it.

**Comment by sagikazarmark** [comment]
Let's go with plugins

**Comment by joelwurtz** [comment]
Fixed in https://github.com/php-http/plugins/commit/8292c356a66a93eabd337a669f580865b3706079

**Comment by dbu** [comment]
sorry, did not want to sound condescending, mark.

i am happy with the new name.

**Comment by sagikazarmark** [comment]
No problem. As said, it was a funny idea, but didn't really make sense.
