### ISSUE TITLE
Throw Client and Server exception in Error plugin

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/plugins#10]
4xx - client
5xx - server

**Comment by joelwurtz** [comment]
I was thinking of something more elaborated for error plugin, a configuration map to transform error code to exception, like an array:

``` php
[
    '404' => 'MyHttpNotFoundException',
    '5[0-9][0-9]' => 'Http\Client\Exception\ServerException',
    ...
]
```

And we can defined the default configuration to be 4xx => client and 5xx => server

However, this would need to make the HttpException constructor final (so we can easily create user defined exception)

**Comment by dbu** [comment]
i don't think you can declare a constructor final, or can you?

otherwise we have to document this and tell people to respect the constructor signature... or maybe we just go with 2 hardcoded exception and allow customization through class extension. like createException(ResponseInterface $response) that you can overwrite and use your own plugin...

**Comment by sagikazarmark** [comment]
> i don't think you can declare a constructor final, or can you?

You can.

> ust go with 2 hardcoded exception

:+1: 

> like createException(ResponseInterface $response) that you can overwrite and use your own plugin..

I don't think an opinionated approach is bad here. I think we could even stick to 4xx and 5xx for simplicity and throw our custom exceptions. It is not that hard to create custom plugins, I am doing it right now as well.

**Comment by dbu** [comment]
ok. lets not have too much flexibility here. if i need my custom
exception (like throw a symfony NotFoundHttpException for 404 only) i
can still add a plugin to the chain that comes closer to upstream that
handles this specific case. or one that extends, and only calls parent::
if the code is not 404.

**Comment by sagikazarmark** [comment]
Agree.
