### ISSUE TITLE
Use getRequestTarget

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/plugins#11]
AFAIK `getRequestTarget` is used to return the full request URI/path so that we don't have to use `(string)$request->getUri()`.

**Comment by joelwurtz** [comment]
:+1: didn't read about this in first place, but have seen it for the LoggerPlugin, so this change was already in my mind.

**Comment by sagikazarmark** [comment]
Will do the change in existing plugins then.

**Comment by joelwurtz** [comment]
Fixed in last commit
