### ISSUE TITLE
Plugin to set timeout

### ISSUE THREAD

**Issue by Nyholm** [php-http/plugins#13]
I have a use case where I want to add a timeout. Could I get some ideas or suggestions how I could implement that?

``` php
// Guzzle6 example to replace
$client = new Client();
$client->request('GET', 'http://example.com', ['timeout' => 1]);
```

**Comment by joelwurtz** [comment]
Not possible :)

**Comment by Nyholm** [comment]
Okey. Thank you for getting back to me. 
=)

**Comment by joelwurtz** [comment]
In fact it's possible but only in the constructor of the guzzle client, but this is not the job of a plugin.
