### ISSUE TITLE
Do not use sendAsyncRequest for synchronous requests

### ISSUE THREAD

**Issue by mekras** [php-http/plugins#14]
PluginClient uses sendAsyncRequest method for synchronous requests. This may lead to overhead and slowdown, because async logic is more complex.

**Comment by dbu** [comment]
i think the reason was to avoid duplicated code. but maybe we can find a way to avoid too much duplication? @joelwurtz would it be enough to create a different $lastCallable depending on what was requested?

**Comment by joelwurtz** [comment]
Maybe the lastest callable can be changed but we have to keep promise
structure
Le 23 nov. 2015 4:19 PM, "David Buchmann" notifications@github.com a
écrit :

**Comment by sagikazarmark** [comment]
I have to agree. Also, if not sticking to promises, we would still have to build a callable chain which would probably end up with the same complexity.

**Comment by dbu** [comment]
agree, we would not want to end up with duplicated code for every plugin. so the EmulateAsyncClient would be what @mekras asks for, right? or where you worried by something else than the actual client call?

**Comment by sagikazarmark** [comment]
Actually, now that all of the logic is moved from the EmulateAsync client to client-tools package, we could move back the EmulateAsyncClient class here and remove the utils dependency.
