### ISSUE TITLE
Plugins planned

### ISSUE THREAD

**Issue by joelwurtz** [php-http/plugins#3]
plugins planned (new or migrate from Ivory):
- [x] Authentication (replaces BasicAuth by @sagikazarmark)
- [x] Cookie (#35, migrate)
- [x] History (migrate)
- [x] Logger (migrate)
- [x] Redirect (migrate)
- [x] Retry (migrate)
- [ ] Tape Recorder (PHP-VCR like by @jeromegamez, see #4)
- [x] Stopwatch (migrate)
- [x] Convert error responses to exceptions (throw exception when status is 4xx / 5xx)
- [ ] Base URI (to complete incomplete requests, see also #37)
- [ ] Validator (validate http request based on protocol (1.0 / 1.1)
- [ ] Sanitizer (add http request headers based on available informations, like Host header, Content-Length header, ...)
- [x] Encoding : Deflate, Chunk, ... (Add header to request to say that we support compression, and decorate stream for deflate / chunk if needed)
- [x] Cache (integration with doctrine / cache, psr 6 ? )

**Comment by jeromegamez** [comment]
Are you okay with me implementing the Tape Recorder part :)? Unless someone else is already at it, of course!

**Comment by joelwurtz** [comment]
No problem go ahead :)

**Comment by sagikazarmark** [comment]
@jeromegamez it's good to see you here. :smile: 

No problem at all, it is your baby anyway.

I was looking at VCR. Do you think there is a possibility to join forces with them? Honestly, I never used these tools too much, just played with them. However, if they are the same, why couldn't we team up with them?

I don't insist on it, I leave this to you, but it would be good to investigate what the possibilities are.

**Comment by sagikazarmark** [comment]
What's the difference between history and logger?

**Comment by dbu** [comment]
@jeromegamez awesome! i created #4 to discuss this in its own thread.

**Comment by joelwurtz** [comment]
> What's the difference between history and logger?

Logger log request / response / exception to a psr/log implementation
History keep trace of http calls (request response couple) in a journal

The real distinction comes from the "couple" thing, in logger plugin there a just some events which may or may be not related, in history the trace is always with the couple

**Comment by sagikazarmark** [comment]
I see. Where is history data kept?

**Comment by joelwurtz** [comment]
The default implementation from ivory http adapter kept data in memory (with a variable), see https://github.com/egeloen/ivory-http-adapter/blob/master/src/Event/History/Journal.php

**Comment by dbu** [comment]
so the history one would be a meta plugin for other tools (like a symfony toolbar integration) to extract what happened during this request?

**Comment by joelwurtz** [comment]
> so the history one would be a meta plugin for other tools (like a symfony toolbar integration) to extract what happened during this request?

Like a data collector thing yes

**Comment by sagikazarmark** [comment]
That sounds good. @dbu can it somehow be added to the HttplugBundle?

**Comment by dbu** [comment]
yes, HttplugBundle would be the right place for integrating the history
plugin with the symfony toolbar

**Comment by joelwurtz** [comment]
Updated the list : 

Compression and Chunk should be in one plugin (Encoding)
Add Cache Plugin (i have see many libraries using cache system to avoid doing to many calls to an api endpoint)

**Comment by sagikazarmark** [comment]
Cache is something that is experimental even in guzzle, would be nice to have. Not sure though whether we need cache if we have VCR or not.

**Comment by joelwurtz** [comment]
I think they all depend on a mutual dependancy like the Formatter / Normalizer thing (which can also be used in the Log plugin), so we can serialize a http request in another format. But despite from that workflow and usage is not the same.

**Comment by dbu** [comment]
cache sounds like a great idea. and while vcr is similar, its not the
same. cache should likely respect the cache header instructions. vcr
should unconditionally cache.

**Comment by jeromegamez** [comment]
VCR even doesn't cache. In VCR's domain, I'm asking you: what is a cache? Has this something to do with those hipster people strolling through the woods searching for treasures? I just know cassettes, racks and my recorder :innocent:

**Comment by jeromegamez** [comment]
But seriously, I also think that the VCR shouldn't be more than that: the notion of a TTL would already be oit of scope.

**Comment by dbu** [comment]
absolutely. however, the mechanics of restoring a response matching some
request from a file is the same as a cache. there might be potential to
share code.

**Comment by sagikazarmark** [comment]
@jeromegamez you probably spent more time with this than me, so I guess you know better, it was just an idea.

However this raises a question: VCR has a storage layer, doesn't it?

I agree, that caching is something else.

**Comment by sagikazarmark** [comment]
Plugins repo is probably on the right way. I think we should not finish all the plugins prior to the stable release. Partly because some components (like caching and formatter) require more planning/duscussion, partly because I don't want to hurry just because stable release, partly because we have other work to do: polishing discovery, message factory, documentation, not to mention the packages used by plugins (authentication, cookie).

We probably have enough plugins implemented for the stable release. There are a few "would be nice to have"s, like Base URI, Sanitizer, Encoding, but I think none of them is requirement.

This repo should also be reviewed. I've already found minor CS errors, I will provide a PR for those.

@joelwurtz @dbu what's the situation with plugin docs? Have anybody written any docs?

**Comment by dbu** [comment]
agree that we should not wait for having lots of plugins implemented for
a 1.0. but we need to see the architectural approach works.

regarding docs: there is only the reminder issue
https://github.com/php-http/documentation/issues/15 . joel, can you
write some documentation for that and i review that? once we have the
general stuff and the already existing plugins documented, it should
also be easier to add doc about each plugin as we add it to the system.

**Comment by joelwurtz** [comment]
Will try to begin some documentation on this tomorrow will do that directly on a branch so you can edit yourself

**Comment by joelwurtz** [comment]
Ok to remove the Timer / Formatter Plugin, they were not plugin in ivory http adapter, just class to add information on the Logger / Journal Plugin ?

**Comment by dbu** [comment]
sounds right.

**Comment by joelwurtz** [comment]
I think with the two plugins already in PR, next work will be on the BaseUri plugin and History plugin, after that we can safely release a first / alpha version of plugin-client (BaseUri is the most needed one i think)

**Comment by sagikazarmark** [comment]
Agree. I would concentrate on BaseURI and cleaning up/proofreading existing code. History plugin can wait I think.

**Comment by dbu** [comment]
does a base uri plugin make sense? i thought we discussed that its not
possible to create messages without a valid uri? or was this plugin
about synchronizing domain in uri and HOST header?

**Comment by sagikazarmark** [comment]
Hm, I remember something about this discussion, but I can't recall where we discussed it.

Also, host is only required for 1.1

**Comment by joelwurtz** [comment]
BaseUri can also be used when you want to add a Prefix for a client,

Like an API which may be accesible under the /api path or not

**Comment by dbu** [comment]
okay. not a blocker for 1.0 then but makes sense.

**Comment by RomeroMsk** [comment]
Hello, guys. Is there any chance to get such plugins?
1. **OAuth v2 authentication**. I think its purpose is obvious.
2. **Page iterator**. Sometimes we need to iterate through several pages, returned by API, to get full collection. So, if we call some API returning the objects collection with pagination (using `X-Pagination-*` headers), with this plugin we could collect all the pages and return the whole response array to the application.

**Comment by sagikazarmark** [comment]
> OAuth v2 authentication

Absolutely, but shouldn't it be an authentication component instead?

https://github.com/php-http/authentication

> Page iterator

I would turn it upside down. Since you actually need the iterator, not the client itself, I would use Pagerfanta with a custom adapter. Although I don't think such a plugin/adapter is easy: you need insights about the content, it's format, etc which doesn't seem to be a responsibility of the HTTP part of your code.

**Comment by RomeroMsk** [comment]
> Absolutely, but shouldn't it be an authentication component instead?

Yes, I think, it's better to make it inside `Authentication`. So, you are planning to implement this soon? It is worth to be included in plugins TODO list then.

> which doesn't seem to be a responsibility of the HTTP part of your code

You're right, will think about additional utility for this.

**Comment by ddeboer** [comment]
@RomeroMsk There’s now [Bearer support](https://github.com/php-http/message/blob/master/src/Authentication/Bearer.php) in php-http/message. Is that sufficient for your needs?

**Comment by RomeroMsk** [comment]
@ddeboer, not it's not enough. Adding the bearer header to request is not a big problem. We need to fetch the token from auth endpoint first and refetch it in case of 401 HTTP Status.

**Comment by Nyholm** [comment]
> @ddeboer, not it's not enough. Adding the bearer header to request is not a big problem. We need to fetch the token from auth endpoint first and refetch it in case of 401 HTTP Status.

How you fetch and refresh a token is very specific to the API. I think it is hard to try to standardize in a http client/plugin.

**Comment by RomeroMsk** [comment]
> How you fetch and refresh a token is very specific to the API. I think it is hard to try to standardize in a http client/plugin.

No, OAuth v2 - is standard. Token is fetching by HTTP request with strictly defined parameters. So it can be standardized in plugin.

**Comment by ddeboer** [comment]
You’re right, @RomeroMsk, the standard OAuth2 flows should be done inside a plugin. Do you have time to work on an OAuth2 plugin?

**Comment by Nyholm** [comment]
Yes, OAuth v2 is standard. But the implementation of it differ. 
Example with a few I've worked with. 

| Vendor | Description |
| --- | --- |
| LinkedIn | They have no refresh functionality, you simply have to reauthenticate. Uses POST request to get token. Uses a `grant_type` parameter. |
| Facebook | Does not have a refresh, Uses GET request to get token. |
| HH.ru | Using a POST request to get and refresh the token. Uses a `grant_type` parameter. |
| Superjob.ru | Using a GET request to get and refresh the token |

**Comment by ddeboer** [comment]
Right, these are (mostly) different implementations of the same [RFC 6749 standard](https://tools.ietf.org/html/rfc6749).
- [Refresh token](https://tools.ietf.org/html/rfc6749#section-1.5) is optional.
- [grant_type](https://tools.ietf.org/html/rfc6749#appendix-A.10) is standard.
- [GET must work; POST is optional](https://tools.ietf.org/html/rfc6749#section-3.1).

**Comment by ddeboer** [comment]
We could have a look at https://github.com/commerceguys/guzzle-oauth2-plugin for inspiration.

**Comment by RomeroMsk** [comment]
> Do you have time to work on an OAuth2 plugin?

Sorry, have no time to work on it now.

> We could have a look at https://github.com/commerceguys/guzzle-oauth2-plugin for inspiration.

Or at this: https://github.com/thephpleague/oauth2-client
Please, note that commerceguys' package is not supporting Guzzle 6 now (https://github.com/commerceguys/guzzle-oauth2-plugin/issues/19).

**Comment by ddeboer** [comment]
Agreed on integration with the phpleague component, as that’s the direction commerceguys seems to take as well.

@sagikazarmark Do we need a separate plugin or only a php-http/message Authentication component?

**Comment by sagikazarmark** [comment]
Hard question, which I am trying to answer for some time. I think the problem is that we can't authenticate and send the original request in one request, which means we need to start at least one new request, which means we need a separate plugin for this.

Another solution would be some kind of Authentication interface which allows doing some extra logic apart from authenticating the request itself.

About league oauth: it looks promising. It would allow us to implement an Authentication method in a nice way. However it uses guzzle 6 internally, which itself is not a problem, but then (at least for now) Guzzle 6 would be a requirement to use our OAuth authentication method. We could probably ask them if they want to use httplug in the future.

**Comment by ddeboer** [comment]
> I think the problem is that we can't authenticate and send the original request in one request, which means we need to start at least one new request, which means we need a separate plugin for this.

True, but the request would be sent by thephpleague/oauth2-client, so either through Guzzle 6 (currently) or later through HTTPlug. As long as our plugin acts on the correct headers (so doesn’t act on OAuth  authentication requests), we’re good.

Is the separate oauth2-client dependency a reason to put the OAuth2 plugin in a separate repo or do we already have plugins with optional (yuck) dependencies?

**Comment by sagikazarmark** [comment]
OK, let's do this. Having it as an authentication method is nicer than having a separate plugin for it.

**Comment by ddeboer** [comment]
Ok, so add it to php-http/message and see how far we get?

**Comment by sagikazarmark** [comment]
Yup.

Do we need at least an authorization code in advance? In most cases we can't confirm access on an authorization page, can we?

**Comment by joelwurtz** [comment]
I think oauth2 will be better integrated with an Oauth2Client implementing HttpClient / HttpAsyncClient and decorating an HttpClient / HttpAsyncClient with the PluginClient for the AuthenticationPlugin

WDYT ?

**Comment by sagikazarmark** [comment]
Why? I think with the plugin system we wanted to avoid such decorations whenever possible.

Also, if we plan to use league oauth, a client wrapper seems to be an overkill.

**Comment by joelwurtz** [comment]
Because Oauth2 is not something which change the request / workflow behavior and is more a standard around http. It will do multiple calls and i find it cleaner as a decorator than a plugin.

**Comment by sagikazarmark** [comment]
> Because Oauth2 is not something which change the request

This is not true, it changes the requests (adds the token).

> It will do multiple calls

That's true, but this is why there is a `$first` callback, isn't it?

> Also, if we plan to use league oauth, a client wrapper seems to be an overkill.

What about this one?

**Comment by dbu** [comment]
lets try to build that plugin and see if it feels iffy. and talk to the league maintainers of oauth to see if they can be interested in httplug.

**Comment by sagikazarmark** [comment]
> lets try to build that plugin

You mean authentication method?

**Comment by dbu** [comment]
sorry, got confused by the issue title and all. yes, authentication method.

**Comment by joelwurtz** [comment]
Closing this, as i think Sanitizer plugin is not useful (separated into other plugins, with the ContentLengthPlugin as an example)

and validator plugin not really a indispensable one, as it does not make sens to have this at runtime IMO

**Comment by guillemcanal** [comment]
Regarding the TapeRecorder plugin (PHP-VCR alike), I did an implementation some time ago. The public API is a big wacky and it need some documentation, but, here you go : https://github.com/eleven-labs/http-replay-plugin
