### ISSUE TITLE
Make psr/log and psr/cache hard dependencies

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/plugins#36]
Those are light, interface packages, probably installed in most projects anyway.

**Comment by joelwurtz** [comment]
:-1: Making this a hard dependancy will force user to have a log and cache implementation

**Comment by sagikazarmark** [comment]
That's not true. I meant the interface packages, not the virtual packages.

**Comment by joelwurtz** [comment]
The interface package does not require a virtual package ?

**Comment by sagikazarmark** [comment]
Nope. And that's how it should be, like on case of HTTPlug: it doesn't require the virtual packages either.

**Comment by joelwurtz** [comment]
Oh ok, sounds good to me then
