### ISSUE TITLE
Make PluginClient properties private?

### ISSUE THREAD

**Issue by xabbuh** [php-http/plugins#39]
I search the issues but didn't find any reasoning for why all properties in the `PluginClient` class are `protected` and not `private`. The same applies to the `configure()` method. This is especially risky for the `options` property as you rely on the `max_restarts` options being set in `createPluginChain()`.

**Comment by sagikazarmark** [comment]
Hm, you are right. Actually, I don't see a reason why the Plugin Client couldn't be final as well. Also, the option resolving logic should work like in the Cache Plugin. Can you provide a PR?

@joelwurtz any objections?

**Comment by Nyholm** [comment]
I agree. Make it final and private.

**Comment by xabbuh** [comment]
see #40
