### ISSUE TITLE
tape recorder php-vcr style

### ISSUE THREAD

**Issue by dbu** [php-http/plugins#4]
build a plugin to intercept and record / replay responses to requests. inspired by http://php-vcr.github.io/ which does this using a stream wrapper around guzzle calls.

**Comment by dbu** [comment]
@jeromegamez: i talked with @adri (one of the maintainers of php-vcr) about this a few weeks ago. he is not sure whether there is much code to share, as php-vcr looks at the raw curl request. 

@adri: if you have any input, please comment here...

psr-7 middleware should allow a much more elegant approach to this than the stream wrappers. in my experience with php-vcr, the challenging part is how to organize data into cassettes (the storage units). organization wise, we maybe should do a separate php-psr7-vcr repository that only cares about psr 7, and a simple plugin in this repository to integrate that system with Httplug. the jobs of recording and restoring are probably too much for a single class - and they could be integrated with psr 7 implementations even when not using Httplug.

**Comment by jeromegamez** [comment]
I would like to have a dedicated repository for a php-psr7-vcr – if someone creates one and gives me access, I'll start right away :innocent:

**Comment by sagikazarmark** [comment]
@jeromegamez note your role in the organization :stuck_out_tongue_winking_eye:

**Comment by dbu** [comment]
given the organisation is called php-http, i think psr7-vcr would be the right name, resulting in `php-http/psr7-vcr`.

**Comment by sagikazarmark** [comment]
I think @jeromegamez already set the repo up.

**Comment by dbu** [comment]
he did. with the name i suggested. unless you changed the repository name right now :-)

**Comment by sagikazarmark** [comment]
Nope. Actually we discussed the name in the private chat and we followed the same logic as you did. :smile:

**Comment by sagikazarmark** [comment]
Can we close this in favor of #3? I think we discussed what needed to be discussed, the rest is up to @jeromegamez :stuck_out_tongue:

**Comment by jeromegamez** [comment]
Of course :)
