### ISSUE TITLE
AutoAuthentication Plugin

### ISSUE THREAD

**Issue by joelwurtz** [php-http/plugins#47]
Actually we have a Authentication Plugin which use a Authentication Interface, it could also be nice to detect authentication from the uri of the request (only for basic auth indeed) like a request to http://user:pass@foo.com

**Comment by sagikazarmark** [comment]
Sounds interesting

**Comment by joelwurtz** [comment]
It should be pretty easy to do as AFAIK the UriInterface already have the user / password field

**Comment by dbu** [comment]
is this something the browser usually does? or does a server handle this? if the later, why would we need to handle it client side?

**Comment by joelwurtz** [comment]
i think this is done by the browser IMO

**Comment by sagikazarmark** [comment]
I think this rather would be an authentication method, not a separate plugin.
