### ISSUE TITLE
Be coherent with the option resolver

### ISSUE THREAD

**Issue by Nyholm** [php-http/plugins#50]
At the moment we use two different styles of configuring the option resolver. Some plugins do it [in the constructor](https://github.com/php-http/plugins/blob/master/src/RetryPlugin.php#L39) and others are doing it in a [separate function](https://github.com/php-http/plugins/blob/master/src/CachePlugin.php#L193). 

I think the code gets easier to read when we have it in a separate function. What do you think?

**Comment by dbu** [comment]
i think having it in the constructor is more readable, as its only 1-2
options so i don't have to jump around in the code to see the
configuration of the resolver.

**Comment by joelwurtz** [comment]
Both way is good for me, but :+1: for consistency

**Comment by Nyholm** [comment]
Ping @sagikazarmark Would you like to make a vote?

**Comment by sagikazarmark** [comment]
Pfff, nope :stuck_out_tongue: 

I agree with @dbu that there is no reason for creating a separate method for one or two options.

An interesting question though: what about caching the resolver? IMO it is part of the Symfony Best Practices, but I am not sure it worths the hassle. In this case, moving the whole stuff to a `getOptionsResolver` method would indeed be better IMO.

**Comment by sagikazarmark** [comment]
About consistency: I am not sure if it's necessary. Extract configureOptions when necessary.

Two common reasons for extraction:
- Allow configuring options in child classes (obviously not the case)
- Extract massive configuration stuff from the constructor (might be the case with many config options)

**Comment by dbu** [comment]
i would agree with those two reasons to extract the configuration, but
think we should default to inline it.

**Comment by Nyholm** [comment]
The only reason I suggest this is for readability and to be coherent. 

Example that I do not think is readable: https://github.com/php-http/plugins/blob/master/src/RedirectPlugin.php#L108

**Comment by Nyholm** [comment]
Okey, lets put it in the constructor.

**Comment by sagikazarmark** [comment]
In the linked case, I would probably extract the stuff. Don't bother with being coherent here, I don't think it matters more than sane logic.

Readability is both your and our reason: extract if too much, don't extract if not, otherwise you have to jump in the code.

**Comment by Nyholm** [comment]
Okey, Thank you.
