### ISSUE TITLE
Use new doc block for documenting array values 

### ISSUE THREAD

**Issue by Nyholm** [php-http/plugins#51]
See [this resource](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#examples-12). Should we make doc blocks like this? 

``` php
    /**
     * @param UriInterface $baseUri
     * @param array        $config {
     *     @var bool $replace True will replace all hosts, false will only add host when none is specified.
     * }
     */
    public function __construct(UriInterface $baseUri, array $config = [])
    {
```

**Comment by dbu** [comment]
if that is something understood by phpdocumentor, i am +1 on switching
for that.

**Comment by sagikazarmark** [comment]
Even if it is not a standard yet, it looks logical to me. :+1:

**Comment by joelwurtz** [comment]
:+1:

**Comment by jeromegamez** [comment]
It looks logical to me as well, my only gripe is that at least PHPStorm doesn't know how to handle the format and will cut off output in hints after the opening curly brace.

**Comment by joelwurtz** [comment]
There is no format for that in PHPStorm or others IDE, but chance is by using this format, it will be extractable in future versions of PHPStorm and others IDE
