### ISSUE TITLE
Options resolver usage

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/plugins#54]
Just a question, but if we are using options resolver, why is it neccessary to extract options from the options array to separate properties?

Apart from making no sense from my point of view, it also goes against the config options array, as you can't add new options without defining the property (which is redundant IMO).

**Comment by dbu** [comment]
so far, the plugins supporting options do not offer extension points for custom options as far as i can see. putting the options into properties improves the readability of the code and prevents typos. so i think it does make sense like it is. inside the class, the constructor with an options array is just an implementation detail.

**Comment by sagikazarmark** [comment]
Fair enough, thanks.
