### ISSUE TITLE
[Cache] Stale

### ISSUE THREAD

**Issue by joelwurtz** [php-http/plugins#56]
Plugin who use the same method as the CachePlugin to determine if the request can be cacheable or not but with the respect_cache_headers to false by default.

However it only return the cached item if there is an exception (error) during the call.

**Comment by dbu** [comment]
good idea. we could optionally support the [stale-if-error](https://tools.ietf.org/html/rfc5861#section-4) cache control if present. with an async client, it could even be possible to return a stale response and update the cache at the same time. not sure if this would be the same plugin or a different one. depends hugely on the usecase whether this makes sense or not.
