### ISSUE TITLE
DNS resolution

### ISSUE THREAD

**Issue by dbu** [php-http/plugins#60]
in https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/issues/283 we found that we should be able to use the `--resolve` option of curl [http://serverfault.com/questions/443949/how-to-test-a-https-url-with-a-given-ip-address](to force the IP of a domain), which translates to [CURLOPT_RESOLVE in php](http://stackoverflow.com/questions/10433016/curl-resolve-equivalent-in-php-curl-library) . 

any idea how we could achieve this in a generic way? to make things more interesting, we need this option at run time, we typically need this when talking to several servers...

**Comment by joelwurtz** [comment]
Don't think it can be generic enough to belong in a plugin, more to a client implementation IMO. 

BTW for talking to multiple servers i have write some issues and beginning work of some stuff in the client-common package, maybe it will be better in this repo or the implementation, WDYT ?

**Comment by sagikazarmark** [comment]
If it is a client implementation, and does not have any dependencies, then client-common is a good place for it.

**Comment by dbu** [comment]
you are right, this belongs to https://github.com/php-http/client-common/issues/9, moved it there
