### ISSUE TITLE
safety catch

### ISSUE THREAD

**Issue by dbu** [php-http/plugins#7]
@dbu
could we have a magic "first" plugin that is inserted by the PluginClient that counts calls and prevents infinite restarts?

@joelwurtz
Not a fan of doing this as the boundaring between infinite restart and many redirection request can be thin sometimes.

@sagikazarmark
This could be a good feature I think, but it should not be automatically added. Can be good in a "fire&forget" situation, where you want to limit the number of restarts.

@dbu
maybe have an option to define how many restarts should be allowed?
we could also just accept a plugin for that, but thats very implicit and
not happening by default. and imho this is something that should happen
by default to protect people not aware of the risk. endless redirects
are pretty simple to create if the server is doing something stupid
(like redirect to the same url you are already on)

@sagikazarmark
An option sounds good to me, but it should be optional. I could imagine a setter for this option value, but the constructor should probably be limited to what we already have there.

@joelwurtz
Actually any plugin using the $first callable or doing retry must implement this mechanism (it's already done in the RetryPlugin and RedirectPlugin) we can maybe provide a SafePluginClient implementation (which extends the current one) to add this behavior ?

@dbu
i would see an `$options` argument to the PluginClient that allows to overwrite a default value (which could be 10 or 20 or something even larger). the thing is that the architecture is prone to endless loops. some people won't read documentation and end up with too many nested calls or even worse things when they run into this with a custom plugin. having something on by default that can be tweaked / disabled sounds better to me.

**Comment by joelwurtz** [comment]
By the way there is already a CircularRedirectionException, should we use it, or add another exception ?

**Comment by sagikazarmark** [comment]
What is it used for? It is not really redirection I think, but a circular thing, so we should probably just rename it to a more generic thing, shouldn't we?

**Comment by joelwurtz** [comment]
Used by the RedirectPlugin when a redirection points to an existing redirection

**Comment by dbu** [comment]
maybe LoopException or something? though the redirect plugin could still
extend it for a specific CircularRedirectionException - that is a server
error and a user might want to target the error specifically (lets say i
build a web crawler or monitoring/testing tool with php)

general loops in the plugins is a programming error

**Comment by sagikazarmark** [comment]
:+1:
